name: Daily Commit

on:
  schedule:
    - cron: "0 12 * * *"
  workflow_dispatch:

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Update activity file
        run: date > activity.txt

      - name: Commit
        run: |
          git config --global user.name "Paulo Mariano"
          git config --global user.email "paulomariano2501@gmail.com"
          git add activity.txt
          git commit -m "Update README.md" || exit 0
          git push
